GET {{base_url}}/applications/103
###
POST {{base_url}}/applications
Content-Type: application/json

{
  "name": "Test Application",
  "description": "This is a fun test application",
  "tags": ["kubernetes", {
    "name": "Bep",
    "description": "Another tag?!"
  }]
}