@application_id = 1
### Get application 103
GET {{base_url}}/applications/{{application_id}}
### Create a new application
POST {{base_url}}/applications
Content-Type: application/json

{
  "name": "Test Application",
  "description": "This is a fun test application",
  "tags": ["kubernetes", {
    "name": "Bep",
    "description": "Another tag?!"
  }]
}
### Update an existing application
PUT {{base_url}}/applications/{{application_id}}
Content-Type: application/json

{
  "description": "Crazy"
}
