GET {{base_url}}/monitors
###
GET {{base_url}}/monitors/1
###
GET {{base_url}}/monitors?include-status=true
###
GET {{base_url}}/monitors/1?include-status=true
###
GET {{base_url}}/monitors/1/history
###
GET {{base_url}}/monitors/1/history?condensed=true
###
POST {{base_url}}/monitors
Content-Type: application/json

{
    "application id": 1,
    "name": "Test",
    "type": "WEB",
    "url": "https://zgamelogic.com/health",
    "regex": "Healthy"
}
###
POST {{base_url}}/monitors/test
Content-Type: application/json

{
  "name": "Test",
  "type": "WEB",
  "url": "https://zgamelogic.com/health",
  "regex": "Healthy"
}
###
@put_id = 1
PUT {{base_url}}/monitors/{{put_id}}
Content-Type: application/json

{
  "name": "Ben"
}
###
@delete_id = 1
DELETE {{base_url}}/monitors/{{delete_id}}
