@monitor_id = 152
@application_id = 2

GET {{base_url}}/monitors/{{application_id}}?include-status=true
###
GET {{base_url}}/monitors/{{monitor_id}}
###
GET {{base_url}}/monitors?include-status=true
###
GET {{base_url}}/monitors/{{monitor_id}}?include-status=true
###
GET {{base_url}}/monitors/{{application_id}}/{{monitor_id}}/history
###
DELETE {{base_url}}/monitors/{{monitor_id}}
###
GET {{base_url}}/monitors/1/history?condensed=true
###
POST {{base_url}}/monitors/{{monitor_id}}/active/true
###
POST {{base_url}}/monitors/{{application_id}}
Content-Type: application/json

{
    "name": "Test",
    "type": "WEB",
    "url": "https://zgamelogic.com/health",
    "regex": "Healthy"
}
###
POST {{base_url}}/monitors/test
Content-Type: application/json

{
  "name": "Test",
  "type": "WEB",
  "url": "https://zgamelogic.com/health",
  "regex": "Healthy"
}
###
PUT {{base_url}}/monitors/{{application_id}}/{{monitor_id}}
Content-Type: application/json

{
  "name": "Ben"
}
###
@delete_id = 1
DELETE {{base_url}}/monitors/{{delete_id}}
