@application_id = 1

### Create rock
POST {{base_url}}/rocks/{{application_id}}
content-type: application/json
api-key: 5

{
  "Ben": "{{$random.integer()}}",
  "Reba": "{{$random.integer()}}"
}

### Get rocks
GET {{base_url}}/rocks/{{application_id}}?page=0
api-key: 5