@application_id = 2

### Create rock
POST {{base_url}}/rocks/{{application_id}}
content-type: application/json

{
  "Ben": 26,
  "Reba": 27
}

### Get rocks
GET {{base_url}}/rocks/{{application_id}}?page=0