name: Deploy Monitors Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Stop Monitors Service
        env:
          DATA_OTTER_KEY: ${{ secrets.DATA_OTTER_KEY }}
        run: |
          echo "$DATA_OTTER_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no azureuser@20.40.218.161 'sudo systemctl stop monitors'

      - name: Upload Monitors.jar
        env:
          DATA_OTTER_KEY: ${{ secrets.DATA_OTTER_KEY }}
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no target/Monitors-1.0.0.jar azureuser@20.40.218.161:/monitor/Monitors.jar

      - name: Start Monitors Service
        env:
          DATA_OTTER_KEY: ${{ secrets.DATA_OTTER_KEY }}
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no azureuser@20.40.218.161 'sudo systemctl start monitors'
